"""HTTP and WebSocket server for the browser overlay.

Built on Starlette + uvicorn.  Serves:
  - Static HTML pages for the OBS browser source.
  - Temporary MP3 audio files generated by TTSService.
  - A WebSocket endpoint that pushes BroadcastEvents to connected clients
    and receives playback-done confirmations so files can be cleaned up.

Audio file lifecycle:
  1. MessageHandler writes a UUID-named MP3 to audio_dir.
  2. AudioServer.broadcast() pushes {audio_url, username, emotes} over WebSocket.
  3. The browser plays the audio and fires an 'ended' event on the <audio> element.
  4. The browser sends {"done": "filename.mp3"} back over the WebSocket.
  5. ws_endpoint unlinks the file from audio_dir (path-traversal check included).
"""

import dataclasses
import json
import logging
from pathlib import Path

import uvicorn
from starlette.applications import Starlette
from starlette.requests import Request
from starlette.responses import FileResponse, Response
from starlette.routing import Mount, Route, WebSocketRoute
from starlette.staticfiles import StaticFiles
from starlette.websockets import WebSocket, WebSocketDisconnect

from .handler import BroadcastEvent

LOGGER: logging.Logger = logging.getLogger(__name__)

# Static files (HTML, SVG, GLB) are co-located with this module in voxer/static/
_STATIC_DIR = Path(__file__).parent / "static"


class AudioServer:
    """Starlette-based HTTP + WebSocket server for audio delivery to the browser overlay."""

    def __init__(self, audio_dir: Path, host: str, port: int) -> None:
        """Initialize the audio server with directory and network settings.

        Args:
            audio_dir: Directory from which MP3 files are served and cleaned up.
            host: Host address to bind the HTTP/WebSocket server.
            port: TCP port to listen on.
        """
        self._audio_dir = audio_dir
        self._host = host
        self._port = port
        # Set of active WebSocket connections; used by broadcast() for fan-out.
        # A plain set is fine here because all access happens on the single asyncio thread.
        self._clients: set[WebSocket] = set()
        self._app = self._build_app()

    def _build_app(self) -> Starlette:
        """Build and return the Starlette ASGI application with all routes wired up."""

        async def index(request: Request) -> FileResponse:
            # Full-featured OBS overlay with 3D speaker animation and emote display
            return FileResponse(
                _STATIC_DIR / "index.html",
                headers={"Cache-Control": "no-store"},  # prevent OBS from caching stale JS
            )

        async def simple(request: Request) -> FileResponse:
            # Lightweight alternative overlay without the 3D model
            return FileResponse(
                _STATIC_DIR / "simple.html",
                headers={"Cache-Control": "no-store"},
            )

        async def favicon(request: Request) -> Response:
            # Return an empty body so browsers don't log 404s for /favicon.ico
            return Response(content=b"", media_type="image/x-icon")

        async def ws_endpoint(websocket: WebSocket) -> None:
            """Handle a single WebSocket client connection.

            The protocol is one-directional from server to client (audio events),
            with one client-to-server message type:
              {"done": "filename.mp3"} — client finished playing, delete the file.
            """
            await websocket.accept()
            self._clients.add(websocket)
            LOGGER.info("WebSocket client connected — %d client(s) active", len(self._clients))
            try:
                while True:
                    data = await websocket.receive_text()
                    try:
                        message = json.loads(data)
                    except json.JSONDecodeError:
                        LOGGER.warning("Received malformed WS message: %r", data)
                        continue
                    if filename := message.get("done"):
                        # Path-traversal guard: only allow deletion of files that are
                        # direct children of audio_dir (no ../ or absolute paths).
                        path = (self._audio_dir / filename).resolve()
                        if path.parent == self._audio_dir.resolve():
                            path.unlink(missing_ok=True)
                            LOGGER.debug("Cleaned up audio file: %s", filename)
                        else:
                            LOGGER.warning("Rejected suspicious filename: %r", filename)
            except WebSocketDisconnect:
                LOGGER.info("WebSocket client disconnected — %d client(s) remaining", len(self._clients) - 1)
            finally:
                # Always remove the socket from the active set on any disconnect or error
                self._clients.discard(websocket)

        return Starlette(routes=[
            Route("/", index),
            Route("/simple", simple),
            Route("/favicon.ico", favicon),
            WebSocketRoute("/ws", ws_endpoint),
            # Static files (JS, CSS, GLB model) served from voxer/static/
            Mount("/static", StaticFiles(directory=_STATIC_DIR)),
            # Ephemeral MP3 files served directly from audio_dir
            Mount("/audio", StaticFiles(directory=self._audio_dir)),
        ])

    async def broadcast(self, event: BroadcastEvent) -> None:
        """Send an audio event to all connected WebSocket clients.

        Uses a snapshot of the client set to avoid mutation-during-iteration.
        Stale clients (those that raise on send) are collected and removed after
        the iteration so subsequent messages skip them.

        Args:
            event: BroadcastEvent with audio_url, username, and emotes list.
        """
        if not self._clients:
            LOGGER.debug("No WS clients connected, skipping broadcast")
            return
        LOGGER.info("Broadcasting to %d client(s): %s", len(self._clients), event.audio_url)
        # dataclasses.asdict() recursively converts nested dataclasses (e.g. EmoteItem)
        message = json.dumps(dataclasses.asdict(event))
        dead: set[WebSocket] = set()
        for ws in self._clients:
            try:
                await ws.send_text(message)
            except Exception:
                # Client disconnected between messages; mark for removal
                dead.add(ws)
        if dead:
            LOGGER.warning("Dropped %d stale client(s)", len(dead))
        self._clients -= dead

    async def serve(self) -> None:
        """Start the uvicorn server and block until shutdown.

        Runs as one of the four concurrent tasks in asyncio.gather().
        uvicorn's own logging is silenced (log_level="warning") because
        colorlog handles all application-level output.
        """
        config = uvicorn.Config(
            self._app,
            host=self._host,
            port=self._port,
            log_level="warning",
        )
        server = uvicorn.Server(config)
        await server.serve()
