"""HTTP and WebSocket server for the browser overlay.

Built on Starlette + uvicorn.  Serves:
  - Static HTML pages for the OBS browser source.
  - Temporary MP3 audio files generated by TTSService.
  - A WebSocket endpoint that pushes BroadcastEvents to connected clients
    and receives playback-done confirmations so files can be cleaned up.

Audio file lifecycle:
  1. MessageHandler writes a UUID-named MP3 to audio_dir.
  2. AudioServer.broadcast() pushes {audio_url, username, avatar_url, emotes} over WebSocket.
  3. The browser plays the audio and fires an 'ended' event on the <audio> element.
  4. The browser sends {"done": "filename.mp3"} back over the WebSocket.
  5. _handle_ws passes that name to _delete_played_audio, which unlinks the
     file from audio_dir (path-traversal check included).

Steps 3-5 only ever happen if some browser received the event, so broadcast()
reports how many clients it reached.  When that count is zero — the usual case
while the stream is offline — MessageHandler deletes the file itself, because
no "done" message is ever going to arrive for it.

Some files still slip through both of those: a browser that crashes or is
refreshed mid-playback never sends its "done" message, and neither does one
whose connection drops between receiving the event and finishing the clip.
sweep_audio_dir() deletes what is left over, and reap_audio() runs it on a
timer for the whole life of the process, so audio_dir cannot grow without
bound across a long stream.  That timer judges a clip by how long ago it was
written, which is only a guess at "abandoned", so AudioServer keeps the names
it is still owed a "done" message for (outstanding_files) and the sweep spares
those whatever their age -- the browser plays one clip at a time and can hold a
queue, so an outstanding clip is not an abandoned one.
"""

import asyncio
import contextlib
import dataclasses
import json
import logging
import time
from collections.abc import Callable, Collection, Iterator
from pathlib import Path
from typing import Final

import uvicorn
from starlette.applications import Starlette
from starlette.requests import Request
from starlette.responses import FileResponse, Response
from starlette.routing import Mount, Route, WebSocketRoute
from starlette.staticfiles import StaticFiles
from starlette.websockets import WebSocket, WebSocketDisconnect

from .models import AUDIO_URL_PREFIX, BroadcastEvent

LOGGER: logging.Logger = logging.getLogger(__name__)

# Static files (HTML, SVG, GLB) are co-located with this module in voxer/static/
_STATIC_DIR = Path(__file__).parent / "static"

# The only key the browser is allowed to send us: {"done": "<uuid>.mp3"} means
# playback finished and the file can be deleted.  Named here because this is
# the whole client-to-server protocol; voxer/static/overlay.js points at this
# constant, so the two halves of the protocol are findable from each other.
DONE_FIELD: Final[str] = "done"


def _overlay_page(name: str) -> FileResponse:
    """Serve one of the overlay HTML pages out of voxer/static/.

    The two pages differ only in which file they send, so the response they
    share is built here.  `Cache-Control: no-store` is part of the contract
    rather than an incidental header: OBS keeps its own HTTP cache, and a
    cached page keeps running the JavaScript that was current when the browser
    source was first added, so an updated overlay would never reach the stream
    until someone recreated the source by hand.

    Args:
        name: File name inside voxer/static/, e.g. "index.html".
    """
    return FileResponse(_STATIC_DIR / name, headers={"Cache-Control": "no-store"})


def resolve_audio_file(audio_dir: Path, filename: str) -> Path | None:
    """Resolve a client-supplied audio filename to a path inside audio_dir.

    Returns None for anything that would escape the directory (path traversal
    via "../", absolute paths, subdirectories) — the client controls this
    string, so it must never be trusted to address arbitrary files.
    """
    path = (audio_dir / filename).resolve()
    if path.parent != audio_dir.resolve():
        return None
    return path


def sweep_audio_dir(
    audio_dir: Path,
    min_age_secs: float = 0.0,
    spare: Collection[str] = (),
) -> int:
    """Delete leftover MP3s from audio_dir and report how many were removed.

    Everything in audio_dir is a temporary clip: it is written just before it
    is broadcast and is meant to be deleted the moment the browser reports that
    it finished playing.  A file that is still there long afterwards is one
    whose "done" message never arrived — the browser crashed, the viewer hit
    refresh in the middle of the clip, or the WebSocket dropped between the two
    events.  Nothing else ever removes those, so without this they accumulate
    for as long as the bot runs.

    Args:
        audio_dir: The directory MP3s are written to and served from.  A
            directory that does not exist is not an error; there is simply
            nothing to sweep.
        min_age_secs: How old a file must be, in seconds since it was last
            written, before it is considered abandoned.  The default of 0 means
            "every file counts", which is what the sweep at startup wants: the
            process that could have been playing them is gone, so all of them
            are stale.  A running bot passes a real age instead, because a file
            created seconds ago may still be on its way to a browser, and
            deleting it then would cut a clip off mid-sentence.
        spare: File names to leave alone whatever their age.  Age is only ever
            a guess at "nobody is coming back for this", and it is a bad guess
            for a clip the overlay has been told about but has not finished
            playing: the browser queues events and plays them one at a time, so
            a busy chat -- or a browser tab that is waiting for the viewer to
            click before it is allowed to play audio at all -- can leave a file
            legitimately outstanding for far longer than any threshold.
            AudioServer passes the names it is still expecting a "done" message
            for, so those are never judged by age.  Empty by default, which is
            what the startup sweep wants: nothing can be outstanding yet.

    Returns:
        The number of files actually deleted, so the caller can decide whether
        there is anything worth logging.
    """
    cutoff = time.time() - min_age_secs
    removed = 0
    for mp3 in audio_dir.glob("*.mp3"):
        if mp3.name in spare:
            continue
        try:
            # With no minimum age every file qualifies, so the modification
            # time is not consulted at all — asking for it would add a way to
            # fail (and a way for a clock skewed into the future to make the
            # startup sweep keep a file it is supposed to remove).
            if min_age_secs > 0 and mp3.stat().st_mtime > cutoff:
                continue
            mp3.unlink()
        except OSError:
            # Either the file went away between the listing and now, or it is
            # not ours to delete (a permission problem on a mounted volume).
            # Neither is worth interrupting the sweep for: the next pass will
            # try again, and debug logging keeps the detail available.
            LOGGER.debug("Could not remove %s", mp3, exc_info=True)
            continue
        removed += 1
    return removed


async def reap_audio(
    audio_dir: Path,
    interval: float,
    min_age: float,
    outstanding: Callable[[], Collection[str]] = lambda: (),
) -> None:
    """Sweep audio_dir on a timer, for as long as the application runs.

    This is one of the long-running coroutines the composition root starts in
    its asyncio.TaskGroup (voxer/app.py), which is also how it is stopped: at
    shutdown the task is cancelled while it waits, and the cancellation ends
    the loop.  It needs no lifecycle of its own.

    The first sweep happens after `interval`, not immediately, because startup
    has just swept the directory clean and a file created in the meantime is
    younger than any sensible `min_age`.

    Args:
        audio_dir: The directory to sweep.
        interval: Seconds to wait between sweeps.
        min_age: Minimum age in seconds before a file is deleted — see
            sweep_audio_dir, which does the actual work.
        outstanding: Called once per sweep to ask which file names must be
            spared regardless of age.  A callable rather than a set because the
            answer changes between sweeps: pass AudioServer.outstanding_files
            so each sweep sees the clips the overlay currently owes a "done"
            message for.  The default answers "none", which keeps this function
            usable on its own.
    """
    while True:
        await asyncio.sleep(interval)
        removed = sweep_audio_dir(audio_dir, min_age, outstanding())
        # Silence when there is nothing to do is the point: this runs every few
        # minutes forever, and a line per sweep would bury the events an
        # operator actually reads.  A count that is not zero is worth seeing,
        # because it says clips are being orphaned somewhere.
        if removed:
            LOGGER.info(
                "Reaped %d orphaned audio file(s) older than %ss", removed, min_age
            )


class _QuietServer(uvicorn.Server):
    """A uvicorn server that leaves the process's signal handling alone.

    Out of the box, ``uvicorn.Server.serve()`` is::

        with self.capture_signals():
            await self._serve(sockets)

    and ``capture_signals`` replaces the process-wide handlers for SIGINT
    (Ctrl-C) and SIGTERM (what ``docker stop`` sends) with uvicorn's own,
    restores the previous ones when it exits, and then — after restoring them —
    re-sends any signal it caught to the process with ``signal.raise_signal``.

    That is the right behaviour for `uvicorn myapp:app` on the command line,
    where uvicorn *is* the program.  Here it is not: the server is one of four
    coroutines running under an ``asyncio.TaskGroup`` in voxer/app.py, so a
    library buried inside one task was deciding what the whole program does
    when it is asked to stop, from an unspecified moment after startup onwards.
    The visible damage was on ``docker stop``: the re-sent SIGTERM met the
    default handler again and killed the process immediately, inside the server
    task, so the task group never unwound and the Twitch bot never got to close
    its EventSub session or clean up the audio file it was in the middle of.
    Ctrl-C took the same path and printed a ``BaseExceptionGroup`` traceback
    wrapping the cancelled sibling tasks on the way out.

    Overriding ``capture_signals`` with a context manager that does nothing
    removes uvicorn from the decision entirely.  voxer/app.py installs one
    handler per signal instead, in the one place that knows about every
    component, and stopping is then an ordinary task cancellation.

    Nothing else about the server changes: this class inherits every bit of
    ``uvicorn.Server``, and ``serve()`` still starts and stops it the same way.
    """

    @contextlib.contextmanager
    def capture_signals(self) -> Iterator[None]:
        """Install no signal handlers, restore none, re-send none."""
        yield


class AudioServer:
    """Starlette-based HTTP + WebSocket server for audio delivery to the browser overlay."""

    def __init__(
        self, audio_dir: Path, host: str, port: int, send_timeout: float
    ) -> None:
        """Initialize the audio server with directory and network settings.

        Args:
            audio_dir: Directory from which MP3 files are served and cleaned up.
            host: Host address to bind the HTTP/WebSocket server.
            port: TCP port to listen on.
            send_timeout: Seconds a single client may take to accept one
                broadcast before it is treated as stalled and dropped.  It has
                no default here on purpose: like the host and the port it is a
                deployment setting, and the composition root (voxer/app.py) is
                the one place that reads those from the environment.  Tests
                pass a small value so a deliberately stalled client does not
                make the suite wait.  See broadcast() for what it protects.
        """
        self._audio_dir = audio_dir
        self._host = host
        self._port = port
        self._send_timeout = send_timeout
        # Set of active WebSocket connections; used by broadcast() for fan-out.
        # A plain set is fine here because all access happens on the single asyncio thread.
        self._clients: set[WebSocket] = set()
        # Names of clips handed to at least one browser that have not been
        # reported as played yet.  reap_audio reads this through
        # outstanding_files() so it never deletes a file the overlay is still
        # going to ask for.  Same thread as _clients, so no lock is needed.
        self._outstanding: set[str] = set()
        self._app = self._build_app()

    def outstanding_files(self) -> frozenset[str]:
        """Names of clips a browser has been sent but has not finished playing.

        The audio reaper (reap_audio) calls this once per sweep and spares
        everything it names.  A copy is returned rather than the live set so a
        caller cannot alter the server's state by accident.
        """
        return frozenset(self._outstanding)

    def _build_app(self) -> Starlette:
        """Build the Starlette ASGI application: the complete list of URLs served.

        This is the map of the server, so it holds nothing but the mapping.
        Each route points at a method below, and bound methods work as
        Starlette endpoints exactly as plain functions do.
        """
        return Starlette(
            routes=[
                Route("/", self._handle_index),
                Route("/simple", self._handle_simple),
                Route("/favicon.ico", self._handle_favicon),
                WebSocketRoute("/ws", self._handle_ws),
                # Static files (JS, CSS, GLB model) served from voxer/static/
                Mount("/static", StaticFiles(directory=_STATIC_DIR)),
                # Ephemeral MP3 files served directly from audio_dir
                Mount(AUDIO_URL_PREFIX, StaticFiles(directory=self._audio_dir)),
            ]
        )

    async def _handle_index(self, request: Request) -> FileResponse:
        """Serve the full OBS overlay: 3D speaker animation plus emote display."""
        return _overlay_page("index.html")

    async def _handle_simple(self, request: Request) -> FileResponse:
        """Serve the lightweight overlay: the same events without the 3D model."""
        return _overlay_page("simple.html")

    async def _handle_favicon(self, request: Request) -> Response:
        """Answer /favicon.ico with an empty body so browsers don't log a 404."""
        return Response(content=b"", media_type="image/x-icon")

    async def _handle_ws(self, websocket: WebSocket) -> None:
        """Serve one WebSocket client for as long as its connection lasts.

        The protocol is one-directional from server to client (audio events),
        with one client-to-server message type:
          {"done": "filename.mp3"} — client finished playing, delete the file.
        """
        await websocket.accept()
        self._clients.add(websocket)
        LOGGER.info(
            "WebSocket client connected — %d client(s) active", len(self._clients)
        )
        try:
            while True:
                data = await websocket.receive_text()
                try:
                    message = json.loads(data)
                except json.JSONDecodeError:
                    LOGGER.warning("Received malformed WS message: %r", data)
                    continue
                if not isinstance(message, dict):
                    # Valid JSON but not an object (e.g. 42, null, [1]) —
                    # calling .get() on it would crash this client's handler
                    LOGGER.warning("Received non-object WS message: %r", data)
                    continue
                if filename := message.get(DONE_FIELD):
                    self._delete_played_audio(filename)
        except WebSocketDisconnect:
            # The ordinary way a connection ends: the browser closed the tab or
            # OBS removed the source.  Nothing to report here — the count is
            # logged in the finally block, so that every way out of this method
            # (a disconnect, a cancellation at shutdown, an unexpected error)
            # leaves the same trace instead of only this one.
            pass
        finally:
            # Discard first, then log, so the number printed is the number of
            # clients that are actually left.  The old message computed
            # len(self._clients) - 1 before the removal — a prediction rather
            # than a fact, and one that was wrong whenever two clients dropped
            # at once.
            self._clients.discard(websocket)
            if not self._clients:
                # Nobody is left to send a "done" message, so every clip still
                # outstanding really has been abandoned.  Releasing them here
                # hands them back to the reaper, which would otherwise spare
                # them for the rest of the process's life.
                self._outstanding.clear()
            LOGGER.info(
                "WebSocket client disconnected — %d client(s) remaining",
                len(self._clients),
            )

    def _delete_played_audio(self, filename: str) -> None:
        """Delete one finished MP3, refusing any name that escapes audio_dir.

        The name comes from the browser, so it is untrusted input: a hostile or
        merely buggy overlay could ask for "../../etc/passwd".  A name that does
        not resolve to a direct child of audio_dir is logged and ignored, and
        the connection carries on — a bad message is not a bad client.

        Args:
            filename: The value the browser sent under the "done" key.
        """
        path = resolve_audio_file(self._audio_dir, filename)
        if path is None:
            LOGGER.warning("Rejected suspicious filename: %r", filename)
            return
        self._outstanding.discard(path.name)
        path.unlink(missing_ok=True)
        LOGGER.debug("Cleaned up audio file: %s", filename)

    async def _close_quietly(self, websocket: WebSocket) -> None:
        """Ask one abandoned client to hang up, without waiting on it.

        Dropping a client from `self._clients` stops us sending to it, but its
        own _handle_ws coroutine is still parked in receive_text() with the
        connection open.  Closing prompts that coroutine to finish, so its
        `finally` runs and the connection is released now instead of whenever
        uvicorn's keepalive gets round to noticing.

        Best effort in both directions.  The close frame travels down the very
        socket that has just refused to accept a message, so it could hang for
        exactly the same reason and is given the same deadline; and every
        failure is swallowed, because there is nothing useful left to do about
        a client we have already given up on.  TimeoutError is a subclass of
        Exception, so the one clause below covers the deadline too.
        """
        try:
            async with asyncio.timeout(self._send_timeout):
                await websocket.close()
        except Exception:
            LOGGER.debug("Ignoring failure while closing a client", exc_info=True)

    async def broadcast(self, event: BroadcastEvent) -> int:
        """Send an audio event to all connected clients, and report how many got it.

        Uses a snapshot of the client set to avoid mutation-during-iteration.
        Stale clients (those that raise on send, and those that do not accept
        the message in time) are collected and removed after the iteration so
        subsequent messages skip them.

        Why the count is returned.  The MP3 this event points at is deleted by
        exactly one mechanism: a browser plays it and sends {"done": "<name>"}
        back, which is what makes _delete_played_audio unlink it.  If no client
        received the event, that message is never coming, so the caller has to
        deal with the file itself — see MessageHandler._publish.  Without the
        count it could not tell the difference, and every message spoken while
        the overlay was closed left a file in audio_dir forever.

        Why each send has a deadline.  Clients are served one after another,
        and this coroutine is awaited from the single task that drains the
        message queue.  A browser that stops reading its socket — a paused OBS
        source, a suspended laptop — therefore applies TCP backpressure all the
        way back to speech synthesis.  Nothing raises: the send simply never
        finishes, so the bot goes quiet, the bounded queue fills and incoming
        chat starts being dropped, with no error logged anywhere.  Giving each
        send `send_timeout` seconds turns that into one dropped client.

        Args:
            event: BroadcastEvent with audio_url, username, avatar_url, and emotes list.

        Returns:
            The number of clients the message was handed to; 0 if none are
            connected or none of them accepted it.
        """
        if not self._clients:
            LOGGER.debug("No WS clients connected, skipping broadcast")
            return 0
        LOGGER.info(
            "Broadcasting to %d client(s): %s", len(self._clients), event.audio_url
        )
        # dataclasses.asdict() recursively converts nested dataclasses (e.g. EmoteItem)
        message = json.dumps(dataclasses.asdict(event))
        delivered = 0
        dead: set[WebSocket] = set()
        # Iterate over a snapshot: each send awaits, and during that await the
        # event loop can run _handle_ws, which adds/removes clients — mutating
        # the live set mid-iteration would raise RuntimeError.
        for ws in list(self._clients):
            try:
                async with asyncio.timeout(self._send_timeout):
                    await ws.send_text(message)
            except TimeoutError:
                # Deliberately separate from the failure below, because it is a
                # different situation and deserves to be recognisable in the
                # log: a raising socket is a browser that went away, which is
                # ordinary, while one that accepts nothing for seconds is a
                # browser that is still connected and not reading.  That is the
                # case that used to stall the whole pipeline silently.
                LOGGER.warning(
                    "Overlay client took more than %ss to accept a message — "
                    "dropping it",
                    self._send_timeout,
                )
                dead.add(ws)
                await self._close_quietly(ws)
            except Exception:
                # Nearly always a client that vanished between messages, but it
                # could equally be a bug on our side, and the warning below
                # reports both as "stale client".  Recording the exception here
                # makes the difference visible when someone turns on debug
                # logging.  The clause stays deliberately broad: narrowing it
                # would let an unexpected error escape the loop and skip every
                # client that has not been sent to yet.
                LOGGER.debug("Dropping client after send failure", exc_info=True)
                dead.add(ws)
            else:
                delivered += 1
        if dead:
            LOGGER.warning("Dropped %d stale client(s)", len(dead))
        self._clients -= dead
        if delivered:
            # Some browser now owns this clip and owes us a "done" message for
            # it, so the reaper must not judge it by age until that arrives.
            self._outstanding.add(Path(event.audio_url).name)
        return delivered

    async def serve(self) -> None:
        """Start the uvicorn server and block until shutdown.

        Runs as one of the long-running tasks in the composition root's
        asyncio.TaskGroup (voxer/app.py).
        uvicorn's own logging is silenced (log_level="warning") because
        colorlog handles all application-level output.

        The server is a _QuietServer rather than a plain uvicorn.Server so that
        starting it does not change how the whole process reacts to Ctrl-C and
        to `docker stop` — see that class for the full story.  Shutdown reaches
        this task as an ordinary cancellation from voxer/app.py.
        """
        config = uvicorn.Config(
            self._app,
            host=self._host,
            port=self._port,
            log_level="warning",
        )
        await _QuietServer(config).serve()
